// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://guikdtwcpagcpyqieftm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1aWtkdHdjcGFnY3B5cWllZnRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MTg1MjcsImV4cCI6MjA2MzQ5NDUyN30.SdbUc0LaE4CBuWi-J_-AvdT4RD9E2m7_SRkewfd5s2E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);